let credentials = "";
const message = document.querySelector("#admin-message");
const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character]));
const money = value => `₹ ${Number(value || 0).toLocaleString("en-IN")}`;
const api = async (url, options = {}) => { const response = await fetch(url, { ...options, headers: { "Content-Type": "application/json", Authorization: `Basic ${credentials}`, ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Request failed."); return data; };
const setMessage = text => message.textContent = text;
async function showOrder(id) { const order = await api(`/api/admin/orders/${id}`); document.querySelector("#admin-order-detail").innerHTML = `<h2>Order ${escapeHtml(order.order_number)}</h2><p><strong>${escapeHtml(order.name)}</strong> · ${escapeHtml(order.email)} · ${escapeHtml(order.phone)}</p><p>${escapeHtml(order.shipping_address.address_line_1)}, ${escapeHtml(order.shipping_address.city)}, ${escapeHtml(order.shipping_address.state)} ${escapeHtml(order.shipping_address.postal_code)}</p><p>Status: ${escapeHtml(order.status)} · Payment: ${escapeHtml(order.payment_status)} · Reconciliation: ${escapeHtml(order.reconciliation_status || "none")}</p><ul>${order.items.map(item => `<li>${escapeHtml(item.product_name_snapshot)} × ${Number(item.quantity)} — ${money(item.subtotal)}</li>`).join("")}</ul>${order.reconciliation_status === "required" ? `<button class="button small" data-reconcile-order="${Number(order.id)}">Retry inventory reconciliation</button>` : ""}`; }
async function loadDashboard() { const [products, orders] = await Promise.all([api("/api/admin/products"), api("/api/admin/orders")]); document.querySelector("#admin-products").innerHTML = products.map(product => `<tr><td>${escapeHtml(product.name)}</td><td>${escapeHtml(product.category)}</td><td><input class="admin-stock" type="number" min="0" value="${Number(product.stock)}" data-product-id="${escapeHtml(product.id)}"></td><td>${product.active ? "Yes" : "No"}</td><td><button class="button small" data-save-stock="${escapeHtml(product.id)}">Save</button></td></tr>`).join(""); document.querySelector("#admin-orders").innerHTML = orders.length ? orders.map(order => `<tr><td><button class="button secondary small" data-view-order="${Number(order.id)}">${escapeHtml(order.order_number)}</button></td><td>${escapeHtml(order.name)}<br><small>${escapeHtml(order.email)}</small></td><td>${money(order.total)}</td><td>${escapeHtml(order.payment_status)}${order.reconciliation_status === "required" ? " · action needed" : ""}</td><td><select data-order-status="${Number(order.id)}">${["pending","confirmed","processing","shipped","delivered","cancelled"].map(status => `<option ${status === order.status ? "selected" : ""}>${status}</option>`).join("")}</select></td><td><button class="button small" data-save-order="${Number(order.id)}">Save</button></td></tr>`).join("") : `<tr><td colspan="6">No orders yet.</td></tr>`; document.querySelector("#admin-dashboard").hidden = false; document.querySelector("#admin-login").hidden = true; }
document.querySelector("#admin-login")?.addEventListener("submit", async event => { event.preventDefault(); credentials = btoa(`${document.querySelector("#admin-user").value}:${document.querySelector("#admin-pass").value}`); try { await loadDashboard(); } catch (error) { setMessage(error.message); credentials = ""; } });
document.addEventListener("click", async event => { const stockButton = event.target.closest("[data-save-stock]"), orderButton = event.target.closest("[data-save-order]"), viewButton = event.target.closest("[data-view-order]"), reconcileButton = event.target.closest("[data-reconcile-order]"); try { if (stockButton) { const id = stockButton.dataset.saveStock; const input = document.querySelector(`[data-product-id="${CSS.escape(id)}"]`); await api(`/api/admin/products/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify({ stock: Number(input.value) }) }); setMessage("Stock updated."); } if (orderButton) { const id = orderButton.dataset.saveOrder, status = document.querySelector(`[data-order-status="${id}"]`).value; await api(`/api/admin/orders/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); setMessage("Order status updated."); await loadDashboard(); } if (viewButton) await showOrder(viewButton.dataset.viewOrder); if (reconcileButton) { await api(`/api/admin/orders/${reconcileButton.dataset.reconcileOrder}/reconcile`, { method: "POST", body: "{}" }); setMessage("Inventory reconciliation completed."); await showOrder(reconcileButton.dataset.reconcileOrder); await loadDashboard(); } } catch (error) { setMessage(error.message); } });
