const checkoutForm = document.querySelector("#checkout-form");
const checkoutMessage = document.querySelector("#checkout-message");
const submitButton = checkoutForm?.querySelector("button[type=submit]");
let checkoutProducts = [];
function readCheckoutCart() { try { const value = JSON.parse(localStorage.getItem("barrel-house-cart") || "[]"); return Array.isArray(value) ? value.filter(item => item && typeof item.id === "string" && Number.isInteger(item.quantity) && item.quantity > 0) : []; } catch { return []; } }
let checkoutCart = readCheckoutCart();
const money = value => `₹ ${Number(value || 0).toLocaleString("en-IN")}`;
function showMessage(message, isError = true) { checkoutMessage.textContent = message; checkoutMessage.className = `form-message${isError ? " error" : ""}`; }
function renderSummary() { const items = checkoutCart.map(item => ({ ...item, product: checkoutProducts.find(product => product.id === item.id) })).filter(item => item.product); const summary = document.querySelector("#checkout-items"); if (!items.length) { summary.innerHTML = `<p class="muted">Your collection is empty. <a href="index.html">Return to the catalogue.</a></p>`; if (submitButton) submitButton.disabled = true; return; } summary.innerHTML = items.map(item => `<div class="checkout-item"><span>${item.product.name} × ${item.quantity}</span><strong>${money(item.product.price * item.quantity)}</strong></div>`).join(""); }
async function loadSummary() { const response = await fetch("/api/products"); if (!response.ok) throw new Error("Catalogue could not be loaded."); checkoutProducts = await response.json(); const valid = new Set(checkoutProducts.map(product => product.id)); checkoutCart = checkoutCart.filter(item => valid.has(item.id)); localStorage.setItem("barrel-house-cart", JSON.stringify(checkoutCart)); renderSummary(); const quote = await fetch("/api/checkout/quote", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: checkoutCart }) }); const data = await quote.json(); if (!quote.ok) throw new Error(data.error || "The order quote could not be loaded."); document.querySelector("#checkout-subtotal").textContent = money(data.subtotal); document.querySelector("#checkout-delivery").textContent = money(data.delivery_fee); document.querySelector("#checkout-total").textContent = money(data.total); }
async function createPayment(order) { const response = await fetch("/api/payments/create", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ order_id: order.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Payment setup failed."); await new Promise((resolve, reject) => { const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; script.onload = resolve; script.onerror = () => reject(new Error("Razorpay checkout could not load.")); document.head.append(script); }); const checkout = new Razorpay({ key: data.keyId, amount: data.amount, currency: data.currency, name: "The Barrel House", description: `Order ${data.orderNumber}`, order_id: data.razorpayOrderId, handler: async payment => { try { const verify = await fetch("/api/payments/verify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ order_id: order.id, ...payment }) }); const result = await verify.json(); if (!verify.ok) throw new Error(result.error || "Payment verification failed."); localStorage.removeItem("barrel-house-cart"); location.href = `confirmation.html?order=${encodeURIComponent(result.orderNumber)}&token=${encodeURIComponent(result.publicToken)}`; } catch (error) { showMessage(error.message); if (submitButton) submitButton.disabled = false; } }, modal: { ondismiss: () => { showMessage("Payment was cancelled. Your order remains pending and has not been charged."); if (submitButton) submitButton.disabled = false; } } }); checkout.open(); }
checkoutForm?.addEventListener("submit", async event => { event.preventDefault(); if (submitButton?.disabled) return; submitButton.disabled = true; showMessage("Validating your order…", false); const data = new FormData(checkoutForm); const payload = { customer: { name: data.get("name"), email: data.get("email"), phone: data.get("phone") }, address: { address_line_1: data.get("address_line_1"), address_line_2: data.get("address_line_2"), city: data.get("city"), state: data.get("state"), postal_code: data.get("postal_code"), country: data.get("country") }, age_confirmed: document.querySelector("#age-confirmed").checked, items: checkoutCart }; const idempotencyKey = sessionStorage.getItem("barrel-house-checkout-key") || crypto.randomUUID(); sessionStorage.setItem("barrel-house-checkout-key", idempotencyKey); try { const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Order validation failed."); await createPayment(result.order); } catch (error) { showMessage(error.message); submitButton.disabled = false; } });
loadSummary().catch(error => { showMessage(error.message); if (submitButton) submitButton.disabled = true; });
