import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import express from "express";
import dotenv from "dotenv";
import initSqlJs from "sql.js";

dotenv.config();
const __filename = fileURLToPath(import.meta.url);
const rootDir = path.dirname(__filename);
const publicDir = path.join(rootDir, "public");
const dataDir = path.join(rootDir, "data");
const databasePath = path.resolve(rootDir, process.env.DATABASE_PATH || "./data/barrel-house.sqlite");
const backupPath = `${databasePath}.bak`;
const seedPath = path.join(dataDir, "products.json");
const port = Number(process.env.PORT || 3000);
const app = express();
const orderStates = ["pending", "confirmed", "processing", "shipped", "delivered", "cancelled"];
const allowedTransitions = { pending: ["confirmed", "cancelled"], confirmed: ["processing", "cancelled"], processing: ["shipped", "cancelled"], shipped: ["delivered"], delivered: [], cancelled: [] };
const SQL = await initSqlJs({ locateFile: file => path.join(rootDir, "node_modules", "sql.js", "dist", file) });
fs.mkdirSync(dataDir, { recursive: true });

function loadDatabase() {
    if (!fs.existsSync(databasePath)) return new SQL.Database();
    try { return new SQL.Database(fs.readFileSync(databasePath)); }
    catch (error) { if (!fs.existsSync(backupPath)) throw error; console.error("Primary database could not be opened; loading the backup."); return new SQL.Database(fs.readFileSync(backupPath)); }
}
const db = loadDatabase();
db.run("PRAGMA foreign_keys = ON");
function saveDatabase() {
    const tempPath = `${databasePath}.${process.pid}.tmp`; const fd = fs.openSync(tempPath, "w");
    try { fs.writeSync(fd, Buffer.from(db.export())); fs.fsyncSync(fd); } finally { fs.closeSync(fd); }
    db.run("PRAGMA foreign_keys=ON");
    if (fs.existsSync(databasePath)) fs.copyFileSync(databasePath, backupPath);
    fs.renameSync(tempPath, databasePath);
}
function run(sql, values = []) { const statement = db.prepare(sql); statement.bind(values); statement.step(); statement.free(); }
function all(sql, values = []) { const statement = db.prepare(sql); statement.bind(values); const rows = []; while (statement.step()) rows.push(statement.getAsObject()); statement.free(); return rows; }
function one(sql, values = []) { return all(sql, values)[0] || null; }
function transaction(callback) { db.run("BEGIN IMMEDIATE"); try { const result = callback(); db.run("COMMIT"); saveDatabase(); return result; } catch (error) { db.run("ROLLBACK"); throw error; } }
function columnExists(table, column) { return all(`PRAGMA table_info(${table})`).some(row => row.name === column); }
function addColumn(table, definition) { const column = definition.split(/\s+/)[0]; if (!columnExists(table, column)) db.run(`ALTER TABLE ${table} ADD COLUMN ${definition}`); }

db.run(`
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,category TEXT NOT NULL,description TEXT NOT NULL,type TEXT NOT NULL,origin TEXT NOT NULL,abv TEXT,price INTEGER,image TEXT NOT NULL,stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0),active INTEGER NOT NULL DEFAULT 1,placeholder INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS customers (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,phone TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS addresses (id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER NOT NULL REFERENCES customers(id),name TEXT NOT NULL,phone TEXT NOT NULL,address_line_1 TEXT NOT NULL,address_line_2 TEXT,city TEXT NOT NULL,state TEXT NOT NULL,postal_code TEXT NOT NULL,country TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS orders (id INTEGER PRIMARY KEY AUTOINCREMENT,order_number TEXT NOT NULL UNIQUE,public_token TEXT NOT NULL UNIQUE,customer_id INTEGER NOT NULL REFERENCES customers(id),subtotal INTEGER NOT NULL CHECK(subtotal>=0),delivery_fee INTEGER NOT NULL CHECK(delivery_fee>=0),total INTEGER NOT NULL CHECK(total>=0),currency TEXT NOT NULL DEFAULT 'INR',status TEXT NOT NULL DEFAULT 'pending',payment_status TEXT NOT NULL DEFAULT 'pending',payment_provider_order_id TEXT,payment_id TEXT,shipping_address_json TEXT NOT NULL,age_confirmed INTEGER NOT NULL DEFAULT 0,stock_released INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_items (id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL REFERENCES orders(id),product_id TEXT NOT NULL REFERENCES products(id),product_name_snapshot TEXT NOT NULL,unit_price_snapshot INTEGER NOT NULL CHECK(unit_price_snapshot>=0),quantity INTEGER NOT NULL CHECK(quantity>0),subtotal INTEGER NOT NULL CHECK(subtotal>=0));
CREATE TABLE IF NOT EXISTS payment_events (event_id TEXT PRIMARY KEY,event_type TEXT NOT NULL,provider_order_id TEXT,payment_id TEXT,received_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admin_actions (id INTEGER PRIMARY KEY AUTOINCREMENT,action TEXT NOT NULL,order_id INTEGER,product_id TEXT,remote_address TEXT,created_at TEXT NOT NULL);
`);
const version = one("PRAGMA user_version")?.user_version || 0;
if (version < 1) {
    addColumn("orders", "idempotency_key TEXT"); addColumn("orders", "idempotency_fingerprint TEXT"); addColumn("orders", "reconciliation_status TEXT NOT NULL DEFAULT 'none'"); addColumn("orders", "reconciliation_error TEXT"); addColumn("orders", "payment_creation_started_at TEXT");
    db.run("CREATE UNIQUE INDEX IF NOT EXISTS orders_idempotency_key_idx ON orders(idempotency_key) WHERE idempotency_key IS NOT NULL");
    db.run("CREATE INDEX IF NOT EXISTS addresses_customer_idx ON addresses(customer_id)"); db.run("CREATE INDEX IF NOT EXISTS orders_customer_idx ON orders(customer_id)"); db.run("CREATE INDEX IF NOT EXISTS orders_provider_order_idx ON orders(payment_provider_order_id)"); db.run("CREATE INDEX IF NOT EXISTS orders_payment_idx ON orders(payment_id)"); db.run("CREATE INDEX IF NOT EXISTS order_items_order_idx ON order_items(order_id)"); db.run("CREATE INDEX IF NOT EXISTS order_items_product_idx ON order_items(product_id)"); db.run("PRAGMA user_version=1");
}
// Keep enforcement enabled after schema work as well; this setting is connection-local in SQLite.
db.run("PRAGMA foreign_keys=ON");
saveDatabase();
function seedProducts() { if (one("SELECT id FROM products LIMIT 1")) return; const seed = JSON.parse(fs.readFileSync(seedPath, "utf8")); const now = new Date().toISOString(); transaction(() => seed.forEach(product => run("INSERT INTO products (id,name,slug,category,description,type,origin,abv,price,image,stock,active,placeholder,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", [product.id,product.name,product.id,product.category,product.description,product.type,product.origin,product.abv,product.price,product.image,product.stock||0,product.active?1:0,product.placeholder?1:0,now,now]))); }
seedProducts();
db.run("PRAGMA foreign_keys=ON");
saveDatabase();
const publicProduct = row => ({ id:row.id,name:row.name,slug:row.slug,category:row.category,description:row.description,type:row.type,origin:row.origin,abv:row.abv,price:row.price,image:row.image,available:Boolean(row.active&&row.stock>0&&row.price!=null),placeholder:Boolean(row.placeholder) });
const configuredDeliveryCodes = () => (process.env.DELIVERY_POSTAL_CODES||"").split(",").map(value=>value.trim()).filter(Boolean);
const isServiceable = postalCode => { const codes=configuredDeliveryCodes(); return codes.includes("*")||codes.includes(String(postalCode).trim()); };
const deliveryFee = () => { const fee=Number(process.env.DELIVERY_FEE||0); return Number.isFinite(fee)&&fee>=0?Math.round(fee):0; };
const cleanString = (value,max=200) => typeof value === "string" ? value.trim().slice(0,max) : "";
const validEmail = email => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
function requireItems(items) { if(!Array.isArray(items)||items.length===0||items.length>50) throw new Error("Cart is empty or invalid."); return items.map(item=>{const id=cleanString(item?.id,80);const quantity=Number(item?.quantity);if(!id||!Number.isInteger(quantity)||quantity<1||quantity>99)throw new Error("Each quantity must be a positive whole number.");return{id,quantity};}); }
function authoritativeItems(items) { return requireItems(items).map(item=>{const product=one("SELECT * FROM products WHERE id=? AND active=1",[item.id]);if(!product||product.price==null||product.placeholder)throw new Error("One or more products are unavailable for ordering.");if(product.stock<item.quantity)throw new Error(`${product.name} does not have enough stock.`);return{product,quantity:item.quantity,subtotal:product.price*item.quantity};}); }
function validateCheckout(body) { const customer=body?.customer||{},address=body?.address||{};const fields={name:cleanString(customer.name,120),email:cleanString(customer.email,160).toLowerCase(),phone:cleanString(customer.phone,40),address_line_1:cleanString(address.address_line_1,200),address_line_2:cleanString(address.address_line_2,200),city:cleanString(address.city,100),state:cleanString(address.state,100),postal_code:cleanString(address.postal_code,20),country:cleanString(address.country||"",80)};if(!fields.name||!validEmail(fields.email)||!fields.phone||!fields.address_line_1||!fields.city||!fields.state||!fields.postal_code||!fields.country)throw new Error("Complete customer and delivery details are required.");if(!isServiceable(fields.postal_code))throw new Error("This postal code is not configured as serviceable yet.");if(body.age_confirmed!==true)throw new Error("Age confirmation is required before checkout.");return fields; }
const orderNumber = () => `TBH-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(3).toString("hex").toUpperCase()}`;
const errorResponse = (res,error,status=400) => res.status(status).json({error:error instanceof Error?error.message:String(error)});
const signaturesMatch = (actual,expected) => {const a=Buffer.from(String(actual||"")),b=Buffer.from(String(expected||""));return a.length===b.length&&crypto.timingSafeEqual(a,b);};
const fingerprint = value => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
const authFailures = new Map();
function adminAuth(req,res,next) { const address=req.ip||req.socket.remoteAddress||"unknown",now=Date.now(),recent=(authFailures.get(address)||[]).filter(time=>now-time<600000);authFailures.set(address,recent);if(recent.length>=10)return res.status(429).json({error:"Too many failed admin attempts. Try again later."});const header=req.headers.authorization||"";if(!header.startsWith("Basic "))return res.status(401).set("WWW-Authenticate","Basic realm=The Barrel House Admin").json({error:"Admin authentication required."});const [username,password]=Buffer.from(header.slice(6),"base64").toString("utf8").split(":");const expectedUser=process.env.ADMIN_USERNAME,expectedPassword=process.env.ADMIN_PASSWORD;if(!expectedUser||!expectedPassword||expectedPassword==="replace-this-before-use"||username!==expectedUser||password!==expectedPassword){recent.push(now);authFailures.set(address,recent);return res.status(401).set("WWW-Authenticate","Basic realm=The Barrel House Admin").json({error:"Invalid admin credentials."});}next(); }
function logAdmin(action,req,orderId=null,productId=null) { run("INSERT INTO admin_actions (action,order_id,product_id,remote_address,created_at) VALUES (?,?,?,?,?)",[action,orderId,productId,req.ip||req.socket.remoteAddress||"unknown",new Date().toISOString()]);saveDatabase(); }
const orderPublicResponse = order => ({id:order.id,orderNumber:order.order_number,publicToken:order.public_token,subtotal:order.subtotal,deliveryFee:order.delivery_fee,total:order.total});
const paymentClientData = order => ({keyId:process.env.RAZORPAY_KEY_ID,razorpayOrderId:order.payment_provider_order_id,amount:order.total*100,currency:order.currency,orderNumber:order.order_number,publicToken:order.public_token});
function restoreStock(orderId) { all("SELECT * FROM order_items WHERE order_id=?",[orderId]).forEach(item=>run("UPDATE products SET stock=stock+?,updated_at=? WHERE id=?",[item.quantity,new Date().toISOString(),item.product_id])); }
function markPaymentPaid(providerOrderId,paymentId) { const order=one("SELECT * FROM orders WHERE payment_provider_order_id=?",[providerOrderId]);if(!order)throw new Error("Payment order is not recognized.");if(order.payment_status==="paid")return{status:"already-paid",order};const items=all("SELECT * FROM order_items WHERE order_id=?",[order.id]),now=new Date().toISOString();try{return transaction(()=>{for(const item of items){const product=one("SELECT stock FROM products WHERE id=?",[item.product_id]);if(!product||product.stock<item.quantity)throw new Error("Stock changed before payment confirmation.");}items.forEach(item=>run("UPDATE products SET stock=stock-?,updated_at=? WHERE id=?",[item.quantity,now,item.product_id]));run("UPDATE orders SET payment_status='paid',status='confirmed',payment_id=?,reconciliation_status='none',reconciliation_error=NULL,updated_at=? WHERE id=? AND payment_status='pending'",[paymentId,now,order.id]);return{status:"paid",order:one("SELECT * FROM orders WHERE id=?",[order.id])};});}catch(error){transaction(()=>run("UPDATE orders SET payment_status='paid',payment_id=?,reconciliation_status='required',reconciliation_error=?,updated_at=? WHERE id=?",[paymentId,error.message,now,order.id]));return{status:"reconciliation-required",order:one("SELECT * FROM orders WHERE id=?",[order.id])};} }

app.post("/api/payments/webhook",express.raw({type:"application/json"}),(req,res)=>{const signature=req.headers["x-razorpay-signature"];if(!process.env.RAZORPAY_WEBHOOK_SECRET||!signature)return res.status(400).json({error:"Webhook verification is not configured."});const expected=crypto.createHmac("sha256",process.env.RAZORPAY_WEBHOOK_SECRET).update(req.body).digest("hex");if(!signaturesMatch(signature,expected))return res.status(401).json({error:"Invalid webhook signature."});let event;try{event=JSON.parse(req.body.toString("utf8"));}catch{return res.status(400).json({error:"Invalid webhook payload."});}const eventId=cleanString(event?.id,120);if(!eventId)return res.status(400).json({error:"Webhook event ID is required."});if(one("SELECT event_id FROM payment_events WHERE event_id=?",[eventId]))return res.json({received:true,duplicate:true});const providerOrderId=event?.payload?.payment?.entity?.order_id,paymentId=event?.payload?.payment?.entity?.id||event?.payload?.refund?.entity?.payment_id,paymentEntity=event?.payload?.payment?.entity,matchingOrder=providerOrderId?one("SELECT * FROM orders WHERE payment_provider_order_id=?",[providerOrderId]):null;try{transaction(()=>run("INSERT INTO payment_events (event_id,event_type,provider_order_id,payment_id,received_at) VALUES (?,?,?,?,?)",[eventId,event.event||"unknown",providerOrderId||null,paymentId||null,new Date().toISOString()]));if(event.event==="payment.captured"&&matchingOrder&&paymentEntity.amount===matchingOrder.total*100&&paymentEntity.currency===matchingOrder.currency&&paymentEntity.status==="captured")markPaymentPaid(providerOrderId,paymentId);if(event.event==="payment.failed"&&providerOrderId)transaction(()=>run("UPDATE orders SET payment_status='failed',updated_at=? WHERE payment_provider_order_id=? AND payment_status='pending'",[new Date().toISOString(),providerOrderId]));if(event.event==="refund.processed"&&paymentId)transaction(()=>{const order=one("SELECT * FROM orders WHERE payment_id=? AND payment_status='paid'",[paymentId]);if(order){restoreStock(order.id);run("UPDATE orders SET payment_status='refunded',stock_released=1,updated_at=? WHERE id=?",[new Date().toISOString(),order.id]);}});return res.json({received:true});}catch(error){return errorResponse(res,error,409);}});
app.use(express.json({limit:"100kb"}));
app.get("/api/health",(req,res)=>res.json({ok:true,service:"the-barrel-house",database:"sql.js"}));
app.get("/api/products",(req,res)=>{const category=cleanString(req.query.category,40),search=cleanString(req.query.search,100).toLowerCase();let rows=all("SELECT * FROM products WHERE active=1 ORDER BY category,name");if(category&&category!=="all")rows=rows.filter(row=>row.category===category);if(search)rows=rows.filter(row=>`${row.name} ${row.category} ${row.type} ${row.origin}`.toLowerCase().includes(search));res.json(rows.map(publicProduct));});
app.get("/api/products/:id",(req,res)=>{const product=one("SELECT * FROM products WHERE id=? AND active=1",[req.params.id]);return product?res.json(publicProduct(product)):res.status(404).json({error:"Product not found."});});
app.post("/api/checkout/quote",(req,res)=>{try{const items=authoritativeItems(req.body.items),subtotal=items.reduce((sum,item)=>sum+item.subtotal,0),fee=deliveryFee();res.json({subtotal,delivery_fee:fee,total:subtotal+fee,currency:"INR",serviceable:Boolean(configuredDeliveryCodes().length)});}catch(error){errorResponse(res,error);}});
app.post("/api/orders",(req,res)=>{try{const idempotencyKey=cleanString(req.get("Idempotency-Key")||req.body.idempotency_key,120);if(!idempotencyKey)return res.status(400).json({error:"Idempotency-Key is required."});const customer=validateCheckout(req.body),items=authoritativeItems(req.body.items),subtotal=items.reduce((sum,item)=>sum+item.subtotal,0),fee=deliveryFee(),total=subtotal+fee;const requestFingerprint=fingerprint({customer,items:items.map(item=>({id:item.product.id,quantity:item.quantity})),age_confirmed:true}),existing=one("SELECT * FROM orders WHERE idempotency_key=?",[idempotencyKey]);if(existing){if(existing.idempotency_fingerprint!==requestFingerprint)return res.status(409).json({error:"Idempotency key was already used for a different checkout."});return res.status(200).json({order:orderPublicResponse(existing),payment:{status:existing.payment_status}});}const now=new Date().toISOString();const created=transaction(()=>{let customerRow=one("SELECT * FROM customers WHERE email=?",[customer.email]);if(customerRow)run("UPDATE customers SET name=?,phone=? WHERE id=?",[customer.name,customer.phone,customerRow.id]);else{run("INSERT INTO customers (name,email,phone,created_at) VALUES (?,?,?,?)",[customer.name,customer.email,customer.phone,now]);customerRow=one("SELECT * FROM customers WHERE email=?",[customer.email]);}run("INSERT INTO addresses (customer_id,name,phone,address_line_1,address_line_2,city,state,postal_code,country) VALUES (?,?,?,?,?,?,?,?,?)",[customerRow.id,customer.name,customer.phone,customer.address_line_1,customer.address_line_2,customer.city,customer.state,customer.postal_code,customer.country]);const addressId=one("SELECT last_insert_rowid() AS id").id,number=orderNumber(),token=crypto.randomBytes(18).toString("hex");run("INSERT INTO orders (order_number,public_token,customer_id,subtotal,delivery_fee,total,currency,status,payment_status,shipping_address_json,age_confirmed,idempotency_key,idempotency_fingerprint,reconciliation_status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[number,token,customerRow.id,subtotal,fee,total,"INR","pending","pending",JSON.stringify({...customer,id:addressId}),1,idempotencyKey,requestFingerprint,"none",now,now]);const orderId=one("SELECT last_insert_rowid() AS id").id;items.forEach(item=>run("INSERT INTO order_items (order_id,product_id,product_name_snapshot,unit_price_snapshot,quantity,subtotal) VALUES (?,?,?,?,?,?)",[orderId,item.product.id,item.product.name,item.product.price,item.quantity,item.subtotal]));return one("SELECT * FROM orders WHERE id=?",[orderId]);});res.status(201).json({order:orderPublicResponse(created),payment:{status:"pending"}});}catch(error){errorResponse(res,error);}});
app.get("/api/orders/public/:orderNumber",(req,res)=>{const order=one("SELECT order_number,subtotal,delivery_fee,total,currency,status,payment_status,reconciliation_status,created_at FROM orders WHERE order_number=? AND public_token=?",[req.params.orderNumber,cleanString(req.query.token,100)]);return order?res.json(order):res.status(404).json({error:"Order not found."});});
app.get("/api/payments/status",(req,res)=>{const configured=Boolean(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET);res.json({mode:configured?"razorpay":"deferred",onlinePaymentAvailable:configured,message:configured?"Online payment is available.":"Online payment is currently unavailable. Orders can be recorded as pending payment."});});
const paymentCreationLocks=new Set();
app.post("/api/payments/create",async(req,res)=>{const order=one("SELECT * FROM orders WHERE id=? AND status='pending' AND payment_status='pending'",[Number(req.body.order_id)]);if(!order)return res.status(404).json({error:"Pending order not found."});if(order.payment_provider_order_id&&!order.payment_provider_order_id.startsWith("creating:"))return res.json(paymentClientData(order));if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET)return res.status(503).json({error:"Payment sandbox is not configured. Add Razorpay test credentials to .env."});if(paymentCreationLocks.has(order.id))return res.status(409).json({error:"Payment order creation is already in progress."});paymentCreationLocks.add(order.id);const marker=`creating:${crypto.randomBytes(8).toString("hex")}`;try{transaction(()=>run("UPDATE orders SET payment_provider_order_id=?,payment_creation_started_at=?,updated_at=? WHERE id=? AND payment_status='pending'",[marker,new Date().toISOString(),new Date().toISOString(),order.id]));const response=await fetch("https://api.razorpay.com/v1/orders",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Basic ${Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${process.env.RAZORPAY_KEY_SECRET}`).toString("base64")}`},body:JSON.stringify({amount:order.total*100,currency:order.currency,receipt:order.order_number,notes:{barrel_house_order:order.order_number}})}),paymentOrder=await response.json();if(!response.ok||!paymentOrder.id){transaction(()=>run("UPDATE orders SET payment_provider_order_id=NULL,payment_creation_started_at=NULL,updated_at=? WHERE id=?",[new Date().toISOString(),order.id]));return res.status(502).json({error:"Payment provider rejected the order."});}transaction(()=>run("UPDATE orders SET payment_provider_order_id=?,payment_creation_started_at=NULL,updated_at=? WHERE id=?",[paymentOrder.id,new Date().toISOString(),order.id]));res.json(paymentClientData(one("SELECT * FROM orders WHERE id=?",[order.id])));}catch(error){try{transaction(()=>run("UPDATE orders SET payment_provider_order_id=NULL,payment_creation_started_at=NULL,updated_at=? WHERE id=?",[new Date().toISOString(),order.id]));}catch{}errorResponse(res,error,502);}finally{paymentCreationLocks.delete(order.id);}});
app.use("/api/payments/verify",(req,res,next)=>{const body=req.body||{};if(!Number.isInteger(Number(body.order_id))||!body.razorpay_order_id||!body.razorpay_payment_id||!body.razorpay_signature)return res.status(400).json({error:"Payment verification data is incomplete."});next();});
app.post("/api/payments/verify",async(req,res)=>{const{order_id,razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body,order=one("SELECT * FROM orders WHERE id=? AND payment_provider_order_id=?",[Number(order_id),razorpay_order_id]);if(!order||!razorpay_payment_id||!razorpay_signature||!process.env.RAZORPAY_KEY_SECRET)return res.status(400).json({error:"Payment verification data is incomplete."});const expected=crypto.createHmac("sha256",process.env.RAZORPAY_KEY_SECRET).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest("hex");if(!signaturesMatch(expected,razorpay_signature))return res.status(400).json({error:"Payment signature verification failed."});try{const paymentResponse=await fetch(`https://api.razorpay.com/v1/payments/${encodeURIComponent(razorpay_payment_id)}`,{headers:{Authorization:`Basic ${Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${process.env.RAZORPAY_KEY_SECRET}`).toString("base64")}`}}),payment=await paymentResponse.json();if(!paymentResponse.ok||payment.order_id!==razorpay_order_id||payment.amount!==order.total*100||payment.currency!==order.currency||payment.status!=="captured")return res.status(400).json({error:"Payment provider verification failed."});const result=markPaymentPaid(razorpay_order_id,razorpay_payment_id);res.json({verified:true,reconciliationRequired:result.status==="reconciliation-required",orderNumber:order.order_number,publicToken:order.public_token});}catch(error){errorResponse(res,error,409);}});
app.get("/api/admin/products",adminAuth,(req,res)=>res.json(all("SELECT * FROM products ORDER BY category,name")));
app.patch("/api/admin/products/:id",adminAuth,(req,res)=>{const stock=Number(req.body.stock),active=req.body.active===undefined?null:(req.body.active?1:0);if(!Number.isInteger(stock)||stock<0)return res.status(400).json({error:"Stock must be a non-negative whole number."});if(!one("SELECT id FROM products WHERE id=?",[req.params.id]))return res.status(404).json({error:"Product not found."});transaction(()=>run("UPDATE products SET stock=?,active=COALESCE(?,active),updated_at=? WHERE id=?",[stock,active,new Date().toISOString(),req.params.id]));logAdmin("product-stock-update",req,null,req.params.id);res.json(one("SELECT * FROM products WHERE id=?",[req.params.id]));});
app.get("/api/admin/orders",adminAuth,(req,res)=>res.json(all("SELECT o.id,o.order_number,o.subtotal,o.delivery_fee,o.total,o.currency,o.status,o.payment_status,o.reconciliation_status,o.created_at,c.name,c.email,c.phone FROM orders o JOIN customers c ON c.id=o.customer_id ORDER BY o.created_at DESC")));
app.get("/api/admin/orders/:id",adminAuth,(req,res)=>{const order=one("SELECT o.*,c.name,c.email,c.phone FROM orders o JOIN customers c ON c.id=o.customer_id WHERE o.id=?",[Number(req.params.id)]);if(!order)return res.status(404).json({error:"Order not found."});order.shipping_address=JSON.parse(order.shipping_address_json);order.items=all("SELECT * FROM order_items WHERE order_id=?",[order.id]);delete order.shipping_address_json;res.json(order);});
app.patch("/api/admin/orders/:id",adminAuth,(req,res)=>{const nextStatus=cleanString(req.body.status,30),order=one("SELECT * FROM orders WHERE id=?",[Number(req.params.id)]);if(!order||!orderStates.includes(nextStatus))return res.status(400).json({error:"Invalid order or status."});if(!allowedTransitions[order.status].includes(nextStatus))return res.status(409).json({error:`Cannot move an order from ${order.status} to ${nextStatus}.`});if(["confirmed","processing","shipped","delivered"].includes(nextStatus)&&(order.payment_status!=="paid"||order.reconciliation_status==="required"))return res.status(409).json({error:"Only a paid and reconciled order can be fulfilled."});if(nextStatus==="cancelled"&&order.payment_status==="paid")return res.status(409).json({error:"Paid orders require a verified provider refund before cancellation."});transaction(()=>run("UPDATE orders SET status=?,updated_at=? WHERE id=?",[nextStatus,new Date().toISOString(),order.id]));logAdmin(`order-status-${nextStatus}`,req,order.id);res.json({updated:true,status:nextStatus});});
app.post("/api/admin/orders/:id/reconcile",adminAuth,(req,res)=>{const order=one("SELECT * FROM orders WHERE id=?",[Number(req.params.id)]);if(!order||order.payment_status!=="paid"||order.reconciliation_status!=="required")return res.status(409).json({error:"Order is not awaiting reconciliation."});try{transaction(()=>{const items=all("SELECT * FROM order_items WHERE order_id=?",[order.id]);items.forEach(item=>{const product=one("SELECT stock FROM products WHERE id=?",[item.product_id]);if(!product||product.stock<item.quantity)throw new Error("Stock is still insufficient for reconciliation.");});items.forEach(item=>run("UPDATE products SET stock=stock-?,updated_at=? WHERE id=?",[item.quantity,new Date().toISOString(),item.product_id]));run("UPDATE orders SET status='confirmed',reconciliation_status='resolved',reconciliation_error=NULL,updated_at=? WHERE id=?",[new Date().toISOString(),order.id]);});logAdmin("order-reconciled",req,order.id);res.json({updated:true,status:"confirmed"});}catch(error){errorResponse(res,error,409);}});
app.use(express.static(publicDir,{extensions:["html"]}));
app.use((req,res)=>res.status(404).json({error:"Not found."}));
app.use((error,req,res,next)=>{console.error("Unhandled request error:",error.message);res.status(500).json({error:"Unexpected server error."});});
export { app, db, saveDatabase, markPaymentPaid };
if(process.argv[1]===__filename)app.listen(port,()=>console.log(`The Barrel House server is running at http://localhost:${port}`));
